name: M3U 直播源定时转换

on:
  schedule:
    - cron: "0 */2 * * *"  # 每两小时运行一次
  workflow_dispatch:       # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch and convert M3U
        run: |
          python << 'EOF'
          import requests, os

          url = "https://raw.githubusercontent.com/develop202/migu_video/refs/heads/main/interface.txt"
          resp = requests.get(url)
          resp.raise_for_status()
          lines = resp.text.splitlines()

          # 确保输出文件夹存在
          os.makedirs("专区", exist_ok=True)

          yangshi, weishi = [], []
          current_group = None
          current_name = None

          for i, line in enumerate(lines):
              if line.startswith("#EXTINF"):
                  # 频道名在最后一个逗号后
                  current_name = line.split(",")[-1].strip()
                  if "央视" in line:
                      current_group = "yangshi"
                  elif "卫视" in line:
                      current_group = "weishi"
                  else:
                      current_group = None
              elif line.startswith("http") and current_group and current_name:
                  record = f"{current_name},{line.strip()}"
                  if current_group == "yangshi":
                      yangshi.append(record)
                  elif current_group == "weishi":
                      weishi.append(record)

          with open("专区/央视频道.txt", "w", encoding="utf-8") as f:
              f.write("\n".join(yangshi))

          with open("专区/卫视频道.txt", "w", encoding="utf-8") as f:
              f.write("\n".join(weishi))
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add "专区/央视频道.txt" "专区/卫视频道.txt" || true

          if ! git diff --cached --quiet; then
            git commit -m "更新央视频道和卫视频道直播源 [skip ci]"
            git push
          else
            echo "文件无变化，不推送。"
          fi
