name: M3U 直播源更新到 live.txt

on:
  schedule:
    - cron: "0 */2 * * *"  # 每两小时运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch and merge M3U into live.txt
        run: python .github/workflows/update_live_txt.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add live.txt || true

          if ! git diff --cached --quiet; then
            git commit -m "更新央视频道和卫视频道直播源 [skip ci]"
            git push
          else
            echo "文件无变化，不推送。"
